import NextAuth from "next-auth";
import Twitter from "next-auth/providers/twitter";
import { syncXUserToSupabase } from "./supabase/sync-user";

const authSecret = process.env.AUTH_SECRET;

if (!authSecret) {
  throw new Error(
    "❌ Missing AUTH_SECRET environment variable.\n\n" +
    "This is required for NextAuth (Auth.js) to sign sessions and cookies.\n\n" +
    "How to fix (important for this monorepo setup):\n" +
    "1. Generate a secret:\n" +
    "   node -e \"console.log(require('crypto').randomBytes(32).toString('base64'))\"\n" +
    "2. Create or edit the file at:\n" +
    "   apps/web/.env.local   (NOT the one at the monorepo root)\n" +
    "3. Add this line:\n" +
    "   AUTH_SECRET=the-long-string-you-generated\n\n" +
    "   (You can copy other required vars like AUTH_TWITTER_* and Supabase keys from the root .env.example into this file too.)\n\n" +
    "4. Stop the dev server completely (Ctrl+C) and restart with:\n" +
    "   pnpm --filter=web dev\n\n" +
    "Why here? Because we run the web app with `pnpm --filter=web`, Next.js loads .env files relative to apps/web/."
  );
}

if (!process.env.AUTH_TWITTER_ID || !process.env.AUTH_TWITTER_SECRET) {
  console.warn(
    "⚠️  AUTH_TWITTER_ID or AUTH_TWITTER_SECRET is missing.\n" +
    "The 'Sign in with X' button will not work until you add them to .env.local.\n" +
    "See .env.example for exact instructions (including the required callback URL in the X Developer Portal)."
  );
}

/**
 * Central next-auth v5 configuration (X / Twitter only).
 *
 * - X-only: only the Twitter provider is registered.
 * - On successful sign-in we call the Supabase sync helper (uses service role).
 * - Secret comes from AUTH_SECRET (generated by user).
 */
const nextAuth = NextAuth({
  providers: [
    Twitter({
      clientId: process.env.AUTH_TWITTER_ID,
      clientSecret: process.env.AUTH_TWITTER_SECRET,
    }),
  ],
  callbacks: {
    async signIn({ account, profile }) {
      // Only act on X/Twitter logins
      if (account?.provider === "twitter" && profile) {
        try {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const p = profile as any;
          await syncXUserToSupabase({
            id: p.id ?? p.sub,
            username: p.username,
            name: profile.name ?? undefined,
          });
        } catch (err) {
          console.error("X user sync to Supabase failed (non-fatal for login):", err);
          // Still allow the user to sign in even if the upsert had a transient issue
        }
      }
      return true;
    },
  },
  secret: authSecret,
  // You can add pages, session strategy, etc. here later
});

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const { handlers, auth, signIn, signOut } = nextAuth as any;
